nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  ts-jest@*:
    dependencies:
      fast-json-stable-stringify: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
